ALTER TABLE agents ADD COLUMN IF NOT EXISTS capabilities TEXT[] DEFAULT '{}';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS long_description TEXT;
