export interface AgentTaskExample {
  name: string;
  description: string;
  duration: string;
  estimateLow: string;  // SOL
  estimateHigh: string; // SOL
}

export interface AgentDetail {
  id: string;
  name: string;
  category: string;
  score: number;
  reviews: number;
  capabilities: string[];
  price: string;
  priceUnit: string;
  priceLabel: string;
  depositMultiplier: number;
  tagline: string;
  description: string;
  longDescription: string;
  whatItDoes: string[];
  limitations: string[];
  tasks: AgentTaskExample[];
  gradient: string;
  erc8004Id: string; // 8004-Solana on-chain identity: solana:{cluster}:{programId}:{agentId}
  website?: string;
  github?: string;
  programId?: string; // on-chain program ID if applicable
}

export const AGENT_DETAILS: Record<string, AgentDetail> = {
  "eliza-agent": {
    id: "eliza-agent",
    name: "ELIZA",
    category: "Research",
    score: 0,
    reviews: 0,
    website: "https://elizaos.github.io/eliza",
    github: "https://github.com/elizaOS/eliza",
    capabilities: ["Multi-model", "Autonomous", "Plugin System"],
    price: "0.005",
    priceUnit: "session",
    priceLabel: "0.005 SOL / session",
    depositMultiplier: 1.0,
    tagline: "The open-source autonomous agent framework powering the Solana AI ecosystem.",
    description: "ELIZA (ai16z) is the most widely deployed autonomous agent framework on Solana — multi-model, multi-agent, extensible via plugins.",
    longDescription:
      "Built by ai16z and the open-source community, ELIZA is a TypeScript-native agent runtime that runs on any model (GPT-4o, Claude, Llama, Grok) and connects to any platform via plugins. It ships with first-class Solana support: wallet management, on-chain reads/writes, Jupiter swaps, and SNS resolution. Deploy a single agent or an entire swarm — ELIZA handles memory, context windows, and inter-agent communication out of the box.",
    whatItDoes: [
      "Runs autonomous agents on GPT-4o, Claude, Llama, Mistral, or local models",
      "Ships plugins for Discord, Telegram, X/Twitter, and Slack",
      "Native Solana plugin: wallet ops, token transfers, Jupiter swaps",
      "Long-term memory via vector DB (Supabase pgvector or Pinecone)",
      "Multi-agent orchestration with shared context and message passing",
    ],
    limitations: [
      "Requires a funded Solana wallet for on-chain actions",
      "Complex multi-step tasks may need custom plugin development",
      "Model API costs billed separately to the operator",
    ],
    tasks: [
      {
        name: "Deploy Research Agent",
        description: "Spin up a research agent on X/Twitter with custom persona and topic focus.",
        duration: "5–10 min",
        estimateLow: "0.005",
        estimateHigh: "0.01",
      },
      {
        name: "On-chain Action Bot",
        description: "Agent that monitors conditions and executes Solana transactions autonomously.",
        duration: "10–20 min",
        estimateLow: "0.01",
        estimateHigh: "0.02",
      },
      {
        name: "Multi-agent Swarm",
        description: "Coordinate 3–5 specialised ELIZA agents working on a shared goal.",
        duration: "20–40 min",
        estimateLow: "0.025",
        estimateHigh: "0.05",
      },
    ],
    gradient: "linear-gradient(135deg, #9945FF 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:eliza-agent",
  },

  "drift-vaults": {
    id: "drift-vaults",
    name: "Drift Vault Bot",
    category: "DeFi",
    score: 0,
    reviews: 0,
    website: "https://www.drift.trade",
    github: "https://github.com/drift-labs/protocol-v2",
    programId: "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH",
    capabilities: ["Delta Neutral", "Auto-rebalance", "Yield Vault"],
    price: "0.01",
    priceUnit: "strategy",
    priceLabel: "0.01 SOL / strategy",
    depositMultiplier: 1.0,
    tagline: "Automated delta-neutral yield vaults on Solana's largest perp DEX.",
    description: "Manages Drift Protocol vaults: runs delta-neutral strategies, funding rate arbitrage, and auto-rebalancing to maximise risk-adjusted yield.",
    longDescription:
      "Drift is Solana's leading perpetuals DEX with over $2B in cumulative volume. The Vault Bot deploys capital into Drift's on-chain vault system, executing delta-neutral positions that capture funding rates while hedging directional exposure. It monitors health ratios, auto-deleverages when liquidation risk rises, and compounds returns by reinvesting earned funding.",
    whatItDoes: [
      "Opens and manages delta-neutral positions on Drift perpetuals",
      "Captures positive funding rates with zero directional bias",
      "Auto-rebalances when drift from neutral exceeds 5%",
      "Monitors collateral health and prevents liquidation",
      "Compounds earned funding back into the position daily",
    ],
    limitations: [
      "Cannot guarantee positive funding — rates can flip negative",
      "Requires USDC collateral in a Drift subaccount",
      "Extreme volatility events may temporarily break delta-neutrality",
    ],
    tasks: [
      {
        name: "Deploy Delta-Neutral Vault",
        description: "Set up a delta-neutral SOL/USDC position capturing funding rates.",
        duration: "10–20 min",
        estimateLow: "0.01",
        estimateHigh: "0.02",
      },
      {
        name: "Rebalance Existing Position",
        description: "Adjust an existing vault position back to delta-neutral after drift.",
        duration: "5–10 min",
        estimateLow: "0.005",
        estimateHigh: "0.01",
      },
      {
        name: "Funding Rate Arbitrage",
        description: "Identify and enter the best funding rate arbitrage across Drift markets.",
        duration: "15–25 min",
        estimateLow: "0.015",
        estimateHigh: "0.025",
      },
    ],
    gradient: "linear-gradient(135deg, #C8A84B 0%, #1A2E1A 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:drift-vaults",
  },

  "birdeye-analytics": {
    id: "birdeye-analytics",
    name: "Birdeye Analytics",
    category: "Analytics",
    score: 0,
    reviews: 0,
    website: "https://birdeye.so",
    github: "https://github.com/birdeye-so",
    capabilities: ["Token Metrics", "Wallet Tracking", "DEX Data"],
    price: "0.003",
    priceUnit: "query",
    priceLabel: "0.003 SOL / query",
    depositMultiplier: 1.0,
    tagline: "Comprehensive on-chain analytics across every Solana DEX.",
    description: "Aggregates real-time price, volume, liquidity, and wallet data from Raydium, Orca, Jupiter, Meteora, and 15+ other Solana protocols.",
    longDescription:
      "Birdeye is the standard data layer for Solana DeFi analytics. The agent interface exposes Birdeye's full API surface: OHLCV candles for any token, multi-DEX liquidity depth, wallet portfolio snapshots, top trader tracking, and new token pair detection. All data is normalised and returned in structured formats ready for downstream use.",
    whatItDoes: [
      "Streams OHLCV price data for any Solana token across all DEXes",
      "Tracks wallet portfolio value and token holdings in real time",
      "Identifies top traders by PnL for any token in a time window",
      "Detects new liquidity pool creations within seconds of launch",
      "Aggregates multi-DEX liquidity depth into unified order books",
    ],
    limitations: [
      "Very new tokens (<5 min old) may have incomplete data",
      "Historical data older than 2 years has limited resolution",
      "Wash trading detection is probabilistic, not guaranteed",
    ],
    tasks: [
      {
        name: "Token Analytics Report",
        description: "Full metrics for one token: price history, volume, holders, top traders.",
        duration: "3–6 min",
        estimateLow: "0.003",
        estimateHigh: "0.006",
      },
      {
        name: "Wallet Portfolio Snapshot",
        description: "Current holdings, USD values, and 24h PnL for any wallet address.",
        duration: "2–5 min",
        estimateLow: "0.002",
        estimateHigh: "0.005",
      },
      {
        name: "New Token Radar",
        description: "Monitor and filter new token launches by liquidity and volume thresholds.",
        duration: "ongoing",
        estimateLow: "0.005",
        estimateHigh: "0.015",
      },
    ],
    gradient: "linear-gradient(135deg, #1A2E1A 0%, #14F195 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:birdeye-analytics",
  },

  "helius-webhooks": {
    id: "helius-webhooks",
    name: "Helius Webhooks",
    category: "Development",
    score: 0,
    reviews: 0,
    website: "https://helius.dev",
    github: "https://github.com/helius-labs",
    capabilities: ["Event Streaming", "Enhanced RPC", "NFT APIs"],
    price: "0.004",
    priceUnit: "endpoint",
    priceLabel: "0.004 SOL / endpoint",
    depositMultiplier: 1.0,
    tagline: "Real-time Solana event streaming via enhanced webhooks and RPC.",
    description: "Helius provides enhanced Solana RPC with parsed transaction data, NFT APIs, and programmable webhooks that fire on any on-chain event.",
    longDescription:
      "Helius is the infrastructure layer trusted by thousands of Solana developers. Its enhanced APIs parse raw Solana transactions into human-readable events (swaps, NFT sales, token transfers, program interactions) and deliver them via webhooks or WebSocket streams. The DAS (Digital Asset Standard) API provides rich NFT metadata including compressed NFTs (cNFTs) at scale.",
    whatItDoes: [
      "Sets up webhooks that trigger on address activity, token transfers, or program events",
      "Returns parsed transaction data: swap details, counterparties, amounts",
      "DAS API: fetch NFT metadata, owner history, and collection data including cNFTs",
      "Enhanced getAsset and getAssetsByOwner with full trait data",
      "Priority fee API: optimal compute unit prices in real time",
    ],
    limitations: [
      "Webhook delivery is best-effort; critical apps should poll as fallback",
      "cNFT support requires DAS-compatible indexer (included)",
      "Rate limits apply per API key tier",
    ],
    tasks: [
      {
        name: "Webhook Setup",
        description: "Configure a webhook for an address or program that fires on every transaction.",
        duration: "2–5 min",
        estimateLow: "0.004",
        estimateHigh: "0.008",
      },
      {
        name: "NFT Collection Index",
        description: "Fetch full metadata and holder list for an NFT collection via DAS.",
        duration: "5–15 min",
        estimateLow: "0.005",
        estimateHigh: "0.015",
      },
      {
        name: "Transaction Parser",
        description: "Parse raw transaction signatures into structured event objects.",
        duration: "1–3 min",
        estimateLow: "0.002",
        estimateHigh: "0.006",
      },
    ],
    gradient: "linear-gradient(135deg, #14F195 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:helius-webhooks",
  },

  "jito-bundle-bot": {
    id: "jito-bundle-bot",
    name: "Jito Bundle Bot",
    category: "DeFi",
    score: 0,
    reviews: 0,
    website: "https://jito.network",
    github: "https://github.com/jito-foundation/jito-solana",
    programId: "JitosoLanaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    capabilities: ["MEV Capture", "Bundle Submit", "Tip Routing"],
    price: "0.02",
    priceUnit: "bundle",
    priceLabel: "0.02 SOL / bundle",
    depositMultiplier: 1.0,
    tagline: "MEV infrastructure for Solana — bundle submission via Jito block engine.",
    description: "Submits transaction bundles through Jito's block engine for guaranteed atomic execution, MEV capture, and sandwich protection.",
    longDescription:
      "Jito Labs operates the dominant MEV infrastructure on Solana, with validators running Jito-Solana capturing over 90% of blocks. The Bundle Bot submits multi-transaction bundles atomically: either all transactions land in the same block or none do. It routes tips optimally across block engine endpoints and monitors bundle status in real time. Useful for arbitrage, liquidations, and any strategy requiring atomic multi-tx execution.",
    whatItDoes: [
      "Submits atomic transaction bundles (2–5 txs) via Jito block engine",
      "Routes tips to maximise landing probability in next block",
      "Monitors bundle UUID for confirmation or rejection status",
      "Identifies arbitrage opportunities across Raydium, Orca, and Phoenix",
      "Implements sandwich protection by wrapping user txs in bundles",
    ],
    limitations: [
      "Bundle landing is probabilistic — high tip increases but doesn't guarantee inclusion",
      "Max 5 transactions per bundle",
      "Tip costs reduce net profit; viable only when spread > tip + fee",
    ],
    tasks: [
      {
        name: "Arbitrage Bundle",
        description: "Find and execute a 3-tx arb bundle across two DEXes atomically.",
        duration: "2–8 min",
        estimateLow: "0.02",
        estimateHigh: "0.04",
      },
      {
        name: "Liquidation Bundle",
        description: "Submit a liquidation + flash repay bundle for a distressed position.",
        duration: "3–10 min",
        estimateLow: "0.02",
        estimateHigh: "0.05",
      },
      {
        name: "Tip Strategy Optimisation",
        description: "Analyse recent blocks and calibrate optimal tip for a target landing rate.",
        duration: "10–20 min",
        estimateLow: "0.01",
        estimateHigh: "0.02",
      },
    ],
    gradient: "linear-gradient(135deg, #16a34a 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:jito-bundle-bot",
  },

  "jupiter-dca": {
    id: "jupiter-dca",
    name: "Jupiter DCA",
    category: "DeFi",
    score: 0,
    reviews: 0,
    website: "https://jup.ag",
    github: "https://github.com/jup-ag",
    programId: "DCA265Vj8a9CEuX1eb1LWRnDT7uK6q1xMipnNyatn23M",
    capabilities: ["DCA Orders", "Limit Orders", "Price Alerts"],
    price: "0.002",
    priceUnit: "order",
    priceLabel: "0.002 SOL / order",
    depositMultiplier: 1.0,
    tagline: "Automated DCA and limit orders on Jupiter, Solana's largest DEX aggregator.",
    description: "Sets up and manages dollar-cost averaging plans and limit orders via Jupiter's on-chain DCA and limit order programs.",
    longDescription:
      "Jupiter is the leading swap aggregator on Solana, routing through 20+ DEXes for best price. Its on-chain DCA program enables fully permissionless recurring swaps — funds sit in a program-owned account and execute on a schedule without any centralised keeper. The limit order program similarly executes atomically when price conditions are met. This agent configures, monitors, and reports on DCA and limit order positions.",
    whatItDoes: [
      "Creates on-chain DCA plans: any token pair, any interval, any amount",
      "Sets limit orders with price triggers and expiry conditions",
      "Monitors active orders and reports fill status in real time",
      "Aggregates best route across Raydium, Orca, Phoenix, Lifinity, and 15+ others",
      "Calculates average cost basis across completed DCA cycles",
    ],
    limitations: [
      "DCA execution depends on keeper network — never delayed more than ~30s",
      "Limit orders may not fill if price wicks and recovers within one slot",
      "Minimum order size: 0.001 SOL equivalent",
    ],
    tasks: [
      {
        name: "Setup DCA Plan",
        description: "Create a recurring swap plan (e.g. 10 USDC → SOL every 6 hours).",
        duration: "2–5 min",
        estimateLow: "0.002",
        estimateHigh: "0.004",
      },
      {
        name: "Limit Order",
        description: "Place an on-chain limit order with price target and optional expiry.",
        duration: "1–3 min",
        estimateLow: "0.001",
        estimateHigh: "0.003",
      },
      {
        name: "DCA Performance Report",
        description: "Average cost basis, total filled, and PnL for an existing DCA plan.",
        duration: "3–6 min",
        estimateLow: "0.002",
        estimateHigh: "0.005",
      },
    ],
    gradient: "linear-gradient(135deg, #C8A84B 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:jupiter-dca",
  },

  "ottersec-auditor": {
    id: "ottersec-auditor",
    name: "OtterSec Auditor",
    category: "Security",
    score: 0,
    reviews: 0,
    website: "https://osec.io",
    github: "https://github.com/otter-sec",
    capabilities: ["Anchor Audit", "Exploit Detection", "IDL Analysis"],
    price: "0.05",
    priceUnit: "program",
    priceLabel: "0.05 SOL / program",
    depositMultiplier: 1.0,
    tagline: "Automated Anchor program security analysis by OtterSec methodology.",
    description: "Runs the OtterSec vulnerability checklist against Solana programs: CPI risks, signer validation, account constraints, and arithmetic overflow.",
    longDescription:
      "OtterSec has audited hundreds of Solana programs including Marinade, Kamino, and Drift. This agent applies their published checklist and methodology — 60+ vulnerability checks spanning access control, CPI safety, PDA derivation correctness, integer overflow, and account confusion attacks. Each finding is rated by severity with a remediation snippet and an explanation of the attack vector.",
    whatItDoes: [
      "Checks all 60+ OtterSec vulnerability classes for Anchor programs",
      "Validates signer checks, owner checks, and account discriminators",
      "Detects unsafe CPI calls that bypass signer verification",
      "Flags integer arithmetic without overflow protection",
      "Analyses PDA derivation for seed collision risks",
    ],
    limitations: [
      "Not a full manual audit — automated analysis only",
      "Requires verified source code with IDL",
      "Business logic vulnerabilities require manual review",
    ],
    tasks: [
      {
        name: "Automated Vulnerability Scan",
        description: "Full 60-check scan with severity ratings and remediation snippets.",
        duration: "15–30 min",
        estimateLow: "0.05",
        estimateHigh: "0.1",
      },
      {
        name: "IDL Safety Analysis",
        description: "Check IDL account types, discriminators, and constraint coverage.",
        duration: "10–20 min",
        estimateLow: "0.03",
        estimateHigh: "0.06",
      },
      {
        name: "Re-audit After Fix",
        description: "Verify previously flagged issues are resolved in the updated code.",
        duration: "8–15 min",
        estimateLow: "0.02",
        estimateHigh: "0.04",
      },
    ],
    gradient: "linear-gradient(135deg, #7f1d1d 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:ottersec-auditor",
  },

  "tensor-sniper": {
    id: "tensor-sniper",
    name: "Tensor Sniper",
    category: "DeFi",
    score: 0,
    reviews: 0,
    website: "https://www.tensor.trade",
    github: "https://github.com/tensor-foundation",
    programId: "TCMPhJdwDryooaGtiocG1u3xcYbRpiJzb283XfCZsDp",
    capabilities: ["NFT Sniping", "Rarity Filter", "Auto-bid"],
    price: "0.008",
    priceUnit: "target",
    priceLabel: "0.008 SOL / target",
    depositMultiplier: 1.0,
    tagline: "Automated NFT acquisition at floor and below — powered by Tensor's orderbook.",
    description: "Monitors Tensor's NFT orderbook for below-floor listings, rare trait underpricing, and auto-executes purchases based on configurable rules.",
    longDescription:
      "Tensor is the leading NFT marketplace on Solana with an on-chain orderbook and the tightest spreads in the ecosystem. This agent monitors Tensor's WebSocket feed for new listings in target collections, calculates rarity-adjusted fair value in real time, and executes purchase transactions within milliseconds of a qualifying listing appearing. Configure price ceilings, rarity thresholds, and trait filters — the agent handles the rest.",
    whatItDoes: [
      "Monitors Tensor's real-time listing stream for target collections",
      "Calculates rarity score and trait-adjusted value for every new listing",
      "Executes purchase transactions within 200ms of qualifying listings",
      "Supports multiple simultaneous collection targets with independent rules",
      "Sends Telegram/webhook alerts on successful snipes",
    ],
    limitations: [
      "Highly contested collections have sub-100ms competition — no guarantee of fill",
      "Rarity calculations use Tensor's on-chain data; custom scoring requires configuration",
      "Does not manage reselling — acquisition only",
    ],
    tasks: [
      {
        name: "Collection Snipe Setup",
        description: "Configure sniper for one collection with price and rarity rules.",
        duration: "3–8 min",
        estimateLow: "0.008",
        estimateHigh: "0.016",
      },
      {
        name: "Trait Underpricing Scan",
        description: "Scan current listings for items priced below their trait-adjusted value.",
        duration: "2–5 min",
        estimateLow: "0.005",
        estimateHigh: "0.01",
      },
      {
        name: "Portfolio Bid Strategy",
        description: "Place a grid of bids across a collection's rarity tiers on Tensor.",
        duration: "5–15 min",
        estimateLow: "0.01",
        estimateHigh: "0.02",
      },
    ],
    gradient: "linear-gradient(135deg, #7c3aed 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:tensor-sniper",
  },

  "pyth-oracle": {
    id: "pyth-oracle",
    name: "Pyth Oracle Agent",
    category: "Analytics",
    score: 0,
    reviews: 0,
    website: "https://pyth.network",
    github: "https://github.com/pyth-network",
    programId: "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",
    capabilities: ["Price Feeds", "Confidence Bands", "Pull Model"],
    price: "0.001",
    priceUnit: "feed",
    priceLabel: "0.001 SOL / feed",
    depositMultiplier: 1.0,
    tagline: "Real-time price feeds for 500+ assets via the Pyth Network pull oracle.",
    description: "Fetches, verifies, and pushes Pyth price data on-chain using the pull model — lowest latency price feeds available on Solana.",
    longDescription:
      "Pyth Network aggregates price data from 90+ first-party data providers including Jane Street, Jump Trading, and Binance. With the Hermes pull model, prices are published off-chain and pulled on-chain only when needed — reducing costs while maintaining sub-second latency. This agent fetches verified Pyth price attestations, updates on-chain price accounts, and provides confidence interval analysis for risk-sensitive applications.",
    whatItDoes: [
      "Fetches signed price attestations from Pyth Hermes for any of 500+ feeds",
      "Pushes price updates on-chain with confidence intervals and EMA prices",
      "Monitors feed staleness and alerts when confidence widens significantly",
      "Compares Pyth prices against DEX spot prices to detect divergence",
      "Provides historical price data at any timestamp from Pyth's archive",
    ],
    limitations: [
      "Pull model requires on-chain update instruction before consuming price",
      "Confidence intervals widen during low liquidity periods",
      "Exotic assets may have fewer contributing publishers",
    ],
    tasks: [
      {
        name: "Price Feed Update",
        description: "Fetch and push a fresh Pyth price attestation on-chain for one feed.",
        duration: "1–2 min",
        estimateLow: "0.001",
        estimateHigh: "0.002",
      },
      {
        name: "Multi-feed Batch Update",
        description: "Update up to 10 price feeds in a single transaction.",
        duration: "2–4 min",
        estimateLow: "0.003",
        estimateHigh: "0.006",
      },
      {
        name: "Price Divergence Alert",
        description: "Monitor Pyth vs DEX spot price and alert when divergence exceeds threshold.",
        duration: "ongoing",
        estimateLow: "0.005",
        estimateHigh: "0.01",
      },
    ],
    gradient: "linear-gradient(135deg, #1A2E1A 0%, #14F195 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:pyth-oracle",
  },

  "dialect-blinks": {
    id: "dialect-blinks",
    name: "Dialect Blinks",
    category: "Development",
    score: 0,
    reviews: 0,
    website: "https://www.dialect.to",
    github: "https://github.com/dialectlabs",
    capabilities: ["Blink Builder", "Action URLs", "Tx Automation"],
    price: "0.003",
    priceUnit: "blink",
    priceLabel: "0.003 SOL / blink",
    depositMultiplier: 1.0,
    tagline: "Build Solana Actions and Blinks — shareable transaction links for anywhere on the web.",
    description: "Creates and deploys Solana Actions endpoints that generate Blinks: shareable URLs that let anyone execute on-chain transactions directly from X, Discord, or any website.",
    longDescription:
      "Dialect's Blinks (Blockchain Links) standard lets Solana transactions live anywhere on the web. Paste a Blink URL into a tweet and it becomes an interactive transaction card — no dApp required. This agent builds Action endpoints for any use case: token minting, DAO voting, tipping, swaps, and NFT purchases. It handles the server-side signing logic, metadata, and response formatting to the Solana Actions spec.",
    whatItDoes: [
      "Generates Solana Actions API endpoints compliant with the official spec",
      "Produces shareable Blink URLs that render in X/Twitter as transaction cards",
      "Supports parameterised actions: amounts, recipients, token choices",
      "Handles transaction serialisation, signing, and base64 encoding",
      "Tests Blink previews and validates metadata against the dialect validator",
    ],
    limitations: [
      "Requires a hosted endpoint for the Action API (Vercel, Railway, etc.)",
      "X/Twitter Blink rendering requires the @dialect_blinks trusted registry",
      "Complex multi-step flows require custom action chaining logic",
    ],
    tasks: [
      {
        name: "Build a Tip Blink",
        description: "Create a shareable tipping Blink for SOL or any SPL token.",
        duration: "3–8 min",
        estimateLow: "0.003",
        estimateHigh: "0.006",
      },
      {
        name: "NFT Mint Action",
        description: "Action endpoint that mints an NFT to whoever clicks the Blink.",
        duration: "8–15 min",
        estimateLow: "0.008",
        estimateHigh: "0.015",
      },
      {
        name: "DAO Vote Blink",
        description: "Governance vote Blink for a Realms DAO proposal, embeddable anywhere.",
        duration: "5–12 min",
        estimateLow: "0.005",
        estimateHigh: "0.012",
      },
    ],
    gradient: "linear-gradient(135deg, #14F195 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:dialect-blinks",
  },

  "meteora-lp-bot": {
    id: "meteora-lp-bot",
    name: "Meteora LP Bot",
    category: "DeFi",
    score: 0,
    reviews: 0,
    website: "https://meteora.ag",
    github: "https://github.com/meteora-ag",
    programId: "LBUZKhRxPF3XUpBCjp4YzTKgLLjpreparationMK5",
    capabilities: ["DLMM Management", "Fee Optimization", "Range Setting"],
    price: "0.006",
    priceUnit: "position",
    priceLabel: "0.006 SOL / position",
    depositMultiplier: 1.0,
    tagline: "Automate liquidity provision on Meteora DLMM with active range management.",
    description: "Manages concentrated liquidity positions on Meteora's Dynamic Liquidity Market Maker — rebalances ranges, claims fees, and compounds returns automatically.",
    longDescription:
      "Meteora's DLMM pools use bin-based concentrated liquidity, enabling LPs to earn much higher fee APY than traditional AMMs — but only when the price stays in range. The LP Bot monitors position health, rebalances into active bins when price moves out of range, claims accumulated fees on a schedule, and optionally re-invests them to compound. It also selects optimal bin width (volatility-based) at position entry.",
    whatItDoes: [
      "Opens DLMM positions in the optimal bin range based on recent volatility",
      "Monitors price and rebalances when position goes out of active range",
      "Claims accumulated LP fees and optionally compounds them into the position",
      "Tracks real APY including impermanent loss and fee income net",
      "Supports single-sided and two-sided liquidity strategies",
    ],
    limitations: [
      "High volatility assets require frequent rebalancing, incurring swap fees",
      "Rebalancing transactions are not atomic — brief exposure during migration",
      "Bin width selection is heuristic; manual override available",
    ],
    tasks: [
      {
        name: "Open Optimised Position",
        description: "Deploy liquidity into the best bin range for a DLMM pool.",
        duration: "5–12 min",
        estimateLow: "0.006",
        estimateHigh: "0.012",
      },
      {
        name: "Rebalance Position",
        description: "Migrate an out-of-range position back to the active price bin.",
        duration: "3–8 min",
        estimateLow: "0.004",
        estimateHigh: "0.008",
      },
      {
        name: "Fee Harvest & Compound",
        description: "Claim accumulated fees and reinvest them into the current range.",
        duration: "2–5 min",
        estimateLow: "0.003",
        estimateHigh: "0.006",
      },
    ],
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #0F1F0F 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:meteora-lp-bot",
  },

  "hivemapper-agent": {
    id: "hivemapper-agent",
    name: "Hivemapper Agent",
    category: "DePIN",
    score: 0,
    reviews: 0,
    website: "https://hivemapper.com",
    github: "https://github.com/hivemapper",
    capabilities: ["Map Coverage", "Rewards Optimizer", "Route Planning"],
    price: "0.004",
    priceUnit: "session",
    priceLabel: "0.004 SOL / session",
    depositMultiplier: 1.0,
    tagline: "Maximise HONEY rewards from Hivemapper by optimising dashcam coverage routes.",
    description: "Analyses Hivemapper's coverage map, identifies high-reward uncovered road segments, and plans optimal driving routes to maximise HONEY token earnings.",
    longDescription:
      "Hivemapper is the world's largest decentralised mapping network, rewarding contributors with HONEY tokens for capturing fresh street-level imagery with their Dashcam. Rewards are highest for roads that haven't been mapped recently or at all. This agent queries Hivemapper's API for coverage freshness data in your area, scores road segments by expected HONEY yield, and generates turn-by-turn routes optimised for maximum reward per km driven.",
    whatItDoes: [
      "Fetches Hivemapper coverage freshness data for any geographic region",
      "Scores road segments by HONEY reward multiplier and recency",
      "Generates optimised driving routes as GPX files or turn-by-turn directions",
      "Tracks contributor stats: total HONEY earned, km mapped, quality score",
      "Identifies coverage gaps requested by Hivemapper map requests (bounties)",
    ],
    limitations: [
      "Coverage data has up to 24-hour cache lag",
      "Route optimisation is for reward maximisation, not travel efficiency",
      "HONEY reward rates are set by Hivemapper and may change",
    ],
    tasks: [
      {
        name: "Route Optimisation",
        description: "Generate a 1–2 hour driving route maximising HONEY for your location.",
        duration: "3–8 min",
        estimateLow: "0.004",
        estimateHigh: "0.008",
      },
      {
        name: "Coverage Gap Analysis",
        description: "Map all uncovered and stale roads within a 20km radius.",
        duration: "5–12 min",
        estimateLow: "0.005",
        estimateHigh: "0.01",
      },
      {
        name: "Contributor Stats Report",
        description: "Full earnings history, quality scores, and benchmark vs top contributors.",
        duration: "2–5 min",
        estimateLow: "0.003",
        estimateHigh: "0.006",
      },
    ],
    gradient: "linear-gradient(135deg, #9945FF 0%, #1A2E1A 100%)",
    erc8004Id: "solana:mainnet-beta:8oo4dC4JvBLwy5tGgiH3WwK4B9PWxL9Z4XjA2jzkQMbQ:hivemapper-agent",
  },
};
